homework 5
DSVAG/AndroidAcademyProject pull request #2
Opened 2020-12-23 17:22 UTC by DSVAG

2020-12-28 21:31 UTC, pcfaktor approved these changes
1. Split the "fragments" package by screens;
2. Move each adapter to its screen package (adapter it isn't data layer abstraction);
3. Also, move ViewBinding.kt into the UI layer.
4. Actually, models also aren't abstractions of the data layer.

2020-12-28 21:31 UTC, pcfaktor commented on app/src/main/java/com/dsvag/androidacademyproject/ui/fragments/MovieListFragment.kt
>          binding.moveList.setHasFixedSize(true)
Maybe increase spanCount for landscape mode?

2021-01-04 21:08 UTC, pcfaktor requested changes

2021-01-04 21:08 UTC, pcfaktor commented on app/src/main/java/com/dsvag/androidacademyproject/data/di/AppComponent.kt
> +
Maybe it's time to use DI Framework?

2021-01-04 21:08 UTC, pcfaktor commented on app/src/main/java/com/dsvag/androidacademyproject/data/di/App.kt
> +
Why the App in the data layer? The root of the source would be a better place for it.

2021-01-04 21:08 UTC, pcfaktor commented on app/src/main/java/com/dsvag/androidacademyproject/ui/viewmodels/MoviesViewModel.kt
> +
One of the main points of ViewModel is that your data can survive the configuration changes in it. But you only get data in it.

2021-01-04 21:17 UTC, DSVAG commented on app/src/main/java/com/dsvag/androidacademyproject/data/di/AppComponent.kt
> +
Hilt or dagger?

2021-01-10 19:44 UTC, pcfaktor approved these changes
LGTM

2021-01-12 13:35 UTC, merged